[package]
name = "superconf"
description = "A barebones configuration file made for low-dependency rust applications."
version = "0.4.1"
readme = "README.md"
license = "MIT"
repository = "https://gitlab.com/Owez/superconf"
authors = ["Owez <root@ogriffiths.com>"]
edition = "2018"
